/**
 * spots-taiwan.js - 全台攝影機位資料庫 (使用者提供的實測直播機位清單)
 */

const TAIWAN_SPOTS = [
  {
    id: 'gaomei',
    name: '台中・高美濕地木棧道',
    region: 'central',
    category: 'sunset',
    lat: 24.31284018839888,
    lng: 120.54737671005434,
    elevation: 2,
    difficulty: '木棧道步道平緩',
    recommendedFocal: '16-35mm 超廣角, 24-70mm',
    bestAzimuth: '270° - 295° (台灣海峽海平面)',
    tags: ['天空之鏡', '巨大風車群', '無敵海平線'],
    description: '全台最負盛名的濕地夕陽！一望無際的泥灘地如天空之鏡，風車群與木棧道在漫天紅霞中形成絕美剪影。',
    photoTips: '退潮時走木棧道深入泥灘取景，利用積水倒映天空。',
    traffic: '開車或騎車至高美濕地遊客中心，步行木棧道。',
    liveUrl: 'https://www.youtube.com/watch?v=fjhg3gAnMFg'
  },
  {
    id: 'gaowangliao',
    name: '台中・望高寮',
    region: 'central',
    category: 'sunrise',
    lat: 24.151718912445833,
    lng: 120.58055599700907,
    elevation: 300,
    difficulty: '觀景平台停車即可拍攝',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '70° - 100° (台中盆地日出)',
    tags: ['台中盆地', '日出', '大肚山'],
    description: '俯瞰台中盆地與大肚山系，日出時城市天際線染上金色晨光。',
    photoTips: '可拍攝城市夜景轉日出的縮時序列。',
    traffic: '開車至大肚山望高寮觀景平台。',
    liveUrl: 'https://www.youtube.com/watch?v=lhXXhDyjFtI'
  },
  {
    id: 'jinlongshan',
    name: '南投・金龍山',
    region: 'central',
    category: 'sunrise',
    lat: 24.118486835532135,
    lng: 120.97498228389544,
    elevation: 700,
    difficulty: '觀景平台步行可達',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '80° - 110° (雲海日出)',
    tags: ['雲海', '日出', '魚池鄉'],
    description: '南投知名雲海日出秘境，晨曦破曉時常見翻騰雲海與日月潭群山剪影。',
    photoTips: '雲海生成視當日逆溫層條件而定，建議提前確認雲海機率。',
    traffic: '開車至魚池鄉金龍山觀景平台。',
    liveUrl: 'https://www.youtube.com/watch?v=tEcHWBlxAGM'
  },
  {
    id: 'alishan-shengli',
    name: '嘉義・阿里山生力農場',
    region: 'central',
    category: 'sunrise',
    lat: 23.432136451292212,
    lng: 120.66435735771614,
    elevation: 1400,
    difficulty: '農場周邊平緩好走',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '75° - 95° (玉山群峰日出)',
    tags: ['雲海', '阿里山', '高山日出'],
    description: '阿里山公路旁高人氣雲海日出點，開闊視野可遠眺玉山山脈與翻騰雲海。',
    photoTips: '秋冬雲海機率較高，建議日出前 30 分鐘先卡位。',
    traffic: '沿阿里山公路 (台18線) 開車可達。',
    liveUrl: 'https://www.youtube.com/watch?v=agEzlv9n9Eg'
  },
  {
    id: 'alishan-eryanping',
    name: '嘉義・阿里山二延平步道',
    region: 'central',
    category: 'sunset',
    lat: 23.42464002262141,
    lng: 120.65270096094285,
    elevation: 1450,
    difficulty: '觀景台步行 5 分鐘',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '260° - 285° (玉山群峰夕陽)',
    tags: ['雲海', '夕陽', '阿里山'],
    description: '與生力農場相鄰的熱門雲海夕陽步道，居高臨下可拍攝夕陽染紅雲海與遠山剪影。',
    photoTips: '日落前雲海容易消散，建議提早到場等候光線變化。',
    traffic: '阿里山公路 (台18線) 沿線停車後步行步道。',
    liveUrl: 'https://www.youtube.com/watch?v=j2L_559nCjc'
  },
  {
    id: 'alishan-xiaoluji',
    name: '嘉義・阿里山小笠原山觀景台',
    region: 'central',
    category: 'both',
    lat: 23.50633556703892,
    lng: 120.82379800316035,
    elevation: 2488,
    difficulty: '祝山車站步行 10 分鐘',
    recommendedFocal: '16-35mm, 70-200mm',
    bestAzimuth: '360° 全景環繞 (日出玉山 85°)',
    tags: ['玉山日出', '360度環景', '塔山晚霞'],
    description: '360 度環景木平台，正對玉山主峰日出！晨曦彩霞染紅玉山積雪或翠綠山脊，傍晚則可眺望塔山晚霞雲海。',
    photoTips: '建議搭阿里山森林小火車至祝山站再步行前往，日出前需摸黑上山。',
    traffic: '祝山車站步行 10 分鐘。',
    liveUrl: 'https://www.youtube.com/watch?v=6Y97q9KrhwA'
  },
  {
    id: 'baihe-biyun',
    name: '台南白河・火山碧雲寺',
    region: 'south',
    category: 'sunset',
    lat: 23.325448310944992,
    lng: 120.4802254991732,
    elevation: 270,
    difficulty: '廟埕平緩好走',
    recommendedFocal: '24-70mm',
    bestAzimuth: '260° - 285° (嘉南平原夕陽)',
    tags: ['廟宇', '嘉南平原', '夕陽'],
    description: '俯瞰嘉南平原的百年古寺，夕陽西下時廟埕金色琉璃瓦與滿天霞光相映成趣。',
    photoTips: '可將廟宇飛簷或香爐納入前景，增添人文氛圍。',
    traffic: '開車至白河區火山碧雲寺廟埕。',
    liveUrl: 'https://www.youtube.com/watch?v=zkX6X9p-6iA'
  },
  {
    id: 'erliao',
    name: '台南・左鎮二寮觀日亭',
    region: 'south',
    category: 'sunrise',
    lat: 22.99299131190427,
    lng: 120.40992624428871,
    elevation: 250,
    difficulty: '觀景台步行可達',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '75° - 100° (月世界惡地日出)',
    tags: ['月世界', '惡地地形', '雲海日出'],
    description: '南台灣三大日出秘境之一，月世界惡地地形在晨光與雲海中呈現層次分明的立體光影。',
    photoTips: '惡地溝壑地形適合長焦壓縮，捕捉光影層次。',
    traffic: '開車至左鎮二寮觀日亭停車場。',
    liveUrl: 'https://www.youtube.com/watch?v=xbojeDKjcaM'
  },
  {
    id: 'qixingtan',
    name: '花蓮・新城七星潭月牙灣',
    region: 'east',
    category: 'sunrise',
    lat: 24.13771518032825,
    lng: 121.6590659570023,
    elevation: 5,
    difficulty: '鵝卵石海灘平坦',
    recommendedFocal: '16-35mm 廣角, 搭配慢速快門',
    bestAzimuth: '70° - 90° (太平洋海平面)',
    tags: ['月牙灣', '太平洋日出', '鵝卵石浪花'],
    description: '優美的新月形礫石海灣，正對浩瀚太平洋！旭日從海平面跳出時，晨彩將浪花與光滑石礫染成金色熔岩。',
    photoTips: '慢速快門拍出浪花流動感，鵝卵石可作前景。',
    traffic: '開車或騎車至七星潭風景區。',
    liveUrl: 'https://www.youtube.com/watch?v=qg-aHp2mvS8'
  },
  {
    id: 'sanxiantai',
    name: '台東・成功三仙台八拱跨海步橋',
    region: 'east',
    category: 'sunrise',
    lat: 23.12428403334014,
    lng: 121.40828968445186,
    elevation: 8,
    difficulty: '八拱橋步道好走',
    recommendedFocal: '16-35mm 廣角, 24-70mm',
    bestAzimuth: '80° - 100° (太平洋第一道曙光)',
    tags: ['第一道曙光', '八拱跨海大橋', '海蝕火山岩'],
    description: '全台灣迎接新年第一道曙光的最神聖地標！八拱巨龍橫跨太平洋巨浪，朝霞破曉時海天交映出極致紫紅光暈。',
    photoTips: '以八拱橋為前景引導線，捕捉曙光穿橋而出。',
    traffic: '成功鎮三仙台風景區，步行跨海步橋。',
    liveUrl: 'https://www.youtube.com/watch?v=X_fchztvqI0'
  },
  {
    id: 'huayuan',
    name: '台東・華源曙光觀景台',
    region: 'east',
    category: 'sunrise',
    lat: 22.655120037370978,
    lng: 121.02292067880808,
    elevation: 100,
    difficulty: '觀景台停車即可拍攝',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '75° - 95° (太平洋海灣日出)',
    tags: ['華源海灣', '太平洋日出', '台九線'],
    description: '俯瞰華源海灣弧形海岸線，日出時漸層藍調轉金黃霞光灑落海灣，公路蜿蜒其間。',
    photoTips: '居高臨下可將海灣弧線與台九線公路一併入鏡。',
    traffic: '台9線華源海灣觀景台，開車可達。',
    liveUrl: 'https://www.youtube.com/watch?v=TY4qQElcUrA'
  },
  {
    id: 'dagushan',
    name: '桃園大古山',
    region: 'north',
    category: 'sunset',
    lat: 25.105746562588735,
    lng: 121.28990867601294,
    elevation: 250,
    difficulty: '觀景平台步行可達',
    recommendedFocal: '24-70mm, 70-200mm',
    bestAzimuth: '260° - 285° (桃園台地夕陽)',
    tags: ['桃園台地', '夕陽', '飛機起降'],
    description: '桃園知名夕陽秘境，開闊視野可遠眺桃園台地與夕陽餘暉，天氣好時可見飛機起降劃過天際。',
    photoTips: '可將起降航機軌跡與晚霞一併入鏡。',
    traffic: '開車至大古山觀景平台。',
    liveUrl: 'https://www.youtube.com/watch?v=BxMeMnX6Qqw'
  },
  {
    id: 'yongan',
    name: '桃園永安漁港',
    region: 'north',
    category: 'sunset',
    lat: 24.988000105826483,
    lng: 121.01577075570127,
    elevation: 5,
    difficulty: '漁港堤防平緩好走',
    recommendedFocal: '16-35mm, 24-70mm',
    bestAzimuth: '260° - 290° (台灣海峽夕陽)',
    tags: ['漁港', '觀海橋', '夕陽'],
    description: '桃園海岸線熱門漁港夕陽點，觀海橋與漁船剪影搭配台灣海峽落日餘暉。',
    photoTips: '利用觀海橋線條引導視線，漁船作為剪影前景。',
    traffic: '開車至永安漁港觀海橋周邊。',
    liveUrl: 'https://www.youtube.com/watch?v=tD_a03trUvE'
  }
];

if (typeof window !== 'undefined') {
  window.TAIWAN_SPOTS = TAIWAN_SPOTS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TAIWAN_SPOTS;
}
