/**
 * spots-taiwan.js - 全台 20 大火燒雲與晨昏攝影聖地數據庫
 */

const TAIWAN_SPOTS = [
  // --- 北部地區 ---
  {
    id: 'spot-xiangshan',
    name: '台北・象山六巨石',
    region: 'north',
    category: 'sunset',
    lat: 25.0270,
    lng: 121.5702,
    elevation: 183,
    bestAzimuth: '285° - 305° (西北西)',
    difficulty: '步道階梯 20 分鐘',
    recommendedFocal: '16-35mm 廣角, 70-200mm 特寫',
    description: '全台灣最著名的地標晚霞機位，俯瞰台北 101 與信義區天際線，大景時漫天火雲映照玻璃帷幕。',
    traffic: '捷運象山站 2 號出口步行至靈雲宮登山口',
    tags: ['台北101', '經典夜景', '信義區天際線']
  },
  {
    id: 'spot-dadaocheng',
    name: '台北・大稻埕碼頭',
    region: 'north',
    category: 'sunset',
    lat: 25.0569,
    lng: 121.5074,
    elevation: 5,
    bestAzimuth: '275° - 295° (西方淡水河口)',
    difficulty: '平地極易到達',
    recommendedFocal: '16-24mm 廣角, 24-70mm',
    description: '淡水河畔經典古帆船剪影與寬廣水面倒影，夕陽西沉時水天一色，橘紅火燒漫天倒映。',
    traffic: '捷運北門站或雙連站轉乘公車/步行 15 分鐘',
    tags: ['河岸倒影', '唐山帆船', '貨櫃市集']
  },
  {
    id: 'spot-tamsui',
    name: '新北・淡水漁人碼頭',
    region: 'north',
    category: 'sunset',
    lat: 25.1827,
    lng: 121.4116,
    elevation: 3,
    bestAzimuth: '280° - 300° (台灣海峽海平面)',
    difficulty: '平地觀景木棧道',
    recommendedFocal: '24-70mm, 70-200mm',
    description: '情人橋與海平面落日交織，直接面對台灣海峽無阻擋地平線，出景時天空與海面燃成一片金紅。',
    traffic: '淡海輕軌淡水漁人碼頭站步行 5 分鐘',
    tags: ['情人橋', '海平面落日', '海峽透光窗']
  },
  {
    id: 'spot-jiufen',
    name: '新北・九份不厭亭',
    region: 'north',
    category: 'both',
    lat: 25.0977,
    lng: 121.8491,
    elevation: 530,
    bestAzimuth: '日落 290° / 日出 80°',
    difficulty: '公路旁需自駕或包車',
    recommendedFocal: '70-200mm 望遠, 24-70mm',
    description: '雙溪與瑞芳交界的寂寞公路，山脊線兩側海天一色，火燒雲常伴隨奔騰雲海，氣勢磅礴。',
    traffic: '102 縣道 21K 處，建議自駕前往',
    tags: ['寂寞公路', '芒草山脊', '雲海晨昏']
  },
  {
    id: 'spot-tofu-rock',
    name: '新竹・頭前溪豆腐岩',
    region: 'north',
    category: 'sunset',
    lat: 24.8197,
    lng: 121.0118,
    elevation: 15,
    bestAzimuth: '270° - 290° (西方流水)',
    difficulty: '需踏石而行，注意濕滑',
    recommendedFocal: '16-35mm 廣角, 搭配 ND 減光鏡',
    description: '方塊消波塊如豆腐般整齊排列，搭配潺潺流水慢速長曝，夕陽火燒時河水如絲絹般映照晚霞。',
    traffic: '導航至新竹頭前溪豆腐岩，溪畔有停車空間',
    tags: ['慢門流水', '幾何豆腐岩', '長曝絲絹']
  },

  // --- 中部地區 ---
  {
    id: 'spot-gaomei',
    name: '台中・高美濕地木棧道',
    region: 'central',
    category: 'sunset',
    lat: 24.3120,
    lng: 120.5501,
    elevation: 2,
    bestAzimuth: '270° - 295° (台灣海峽海平面)',
    difficulty: '木棧道步道平緩',
    recommendedFocal: '16-35mm 超廣角, 24-70mm',
    description: '全台最負盛名的濕地夕陽！一望無際的泥灘地如天空之鏡，風車群與木棧道在漫天紅霞中形成絕美剪影。',
    traffic: '清水火車站轉乘 178/179 號公車直達',
    tags: ['天空之鏡', '巨大風車群', '無敵海平線']
  },
  {
    id: 'spot-sunmoonlake',
    name: '南投・日月潭朝霧碼頭',
    region: 'central',
    category: 'sunrise',
    lat: 23.8697,
    lng: 120.9189,
    elevation: 748,
    bestAzimuth: '75° - 95° (東方水社大山)',
    difficulty: '碼頭木棧道極易到達',
    recommendedFocal: '24-70mm, 70-200mm',
    description: '全台日出第一聖地！清晨湖面常有薄霧繚繞，朝霞透過水社大山投射萬丈金芒，宛如國畫潑墨仙境。',
    traffic: '台 21 線朝霧碼頭停車場',
    tags: ['山嵐晨霧', '晨曦金光', '水社大山日出']
  },
  {
    id: 'spot-hehuanshan',
    name: '南投/花蓮・合歡山武嶺與主峰',
    region: 'central',
    category: 'both',
    lat: 24.1371,
    lng: 121.2758,
    elevation: 3275,
    bestAzimuth: '日落 275° / 日出 85°',
    difficulty: '高海拔需禦寒與防高山反應',
    recommendedFocal: '14-24mm 超廣角, 70-200mm',
    description: '台灣公路最高點，高山大氣能見度極致純淨！夕陽翻滾雲海燃燒如熔岩瀑布，日出奇萊群峰金光萬道。',
    traffic: '台 14 甲線武嶺停車場',
    tags: ['百岳雲海', '高海拔純淨空氣', '銀河日落同框']
  },
  {
    id: 'spot-alishan',
    name: '嘉義・阿里山小笠原山觀景台',
    region: 'central',
    category: 'both',
    lat: 23.5139,
    lng: 120.8143,
    elevation: 2488,
    bestAzimuth: '360° 全景環繞 (日出玉山 85°)',
    difficulty: '祝山車站步行 10 分鐘',
    recommendedFocal: '16-35mm, 70-200mm',
    description: '360 度環景木平台，正對玉山主峰日出！晨曦彩霞染紅玉山積雪或翠綠山脊，傍晚則可眺望塔山晚霞雲海。',
    traffic: '阿里山林鐵祝山線至祝山站後步行',
    tags: ['玉山日出', '360度環景', '塔山晚霞']
  },
  {
    id: 'spot-haowangjiao',
    name: '苗栗・後龍好望角',
    region: 'central',
    category: 'sunset',
    lat: 24.6025,
    lng: 120.7303,
    elevation: 85,
    bestAzimuth: '275° - 300° (海線鐵道與風車)',
    difficulty: '觀景平台平坦好走',
    recommendedFocal: '24-70mm, 70-200mm',
    description: '白色巨型風車矗立於海崖上，俯瞰海線火車穿梭於稻田與防風林間，晚霞火燒染紅台灣海峽海岸線。',
    traffic: '台 61 線西濱快速道路赤土崎交流道下',
    tags: ['海線火車', '巨型風車', '海崖全景']
  },

  // --- 南部地區 ---
  {
    id: 'spot-jingzijiao',
    name: '台南・北門井仔腳瓦盤鹽田',
    region: 'south',
    category: 'sunset',
    lat: 23.2589,
    lng: 120.1083,
    elevation: 2,
    bestAzimuth: '265° - 290° (西方濱海鹽田)',
    difficulty: '平地極易到達',
    recommendedFocal: '16-35mm 廣角 (低角度貼近水面)',
    description: '台灣現存最古老瓦盤鹽田，如馬賽克拼貼的結晶池倒映漫天火霞與鹽堆小金字塔，色澤極致夢幻。',
    traffic: '台 17 線轉南 10 鄉道直達',
    tags: ['鹽田倒影', '鹽錐剪影', '極致色彩純淨']
  },
  {
    id: 'spot-erliao',
    name: '台南・左鎮二寮觀日亭',
    region: 'south',
    category: 'sunrise',
    lat: 22.9918,
    lng: 120.4074,
    elevation: 185,
    bestAzimuth: '75° - 95° (東方中央山脈)',
    difficulty: '觀景平台平整好走',
    recommendedFocal: '70-200mm, 100-400mm 長焦',
    description: '全台海拔最低的潑墨山水日出！月世界白堊惡地地形在清晨雲霧繚繞中如水墨畫，晨曦穿透竹林射出金光斜射光。',
    traffic: '國道 3 號新化交流道接南 168 鄉道',
    tags: ['水墨月世界', '晨曦斜射光', '低海拔雲瀑']
  },
  {
    id: 'spot-guanshan',
    name: '屏東・恆春關山夕照',
    region: 'south',
    category: 'sunset',
    lat: 21.9624,
    lng: 120.7188,
    elevation: 152,
    bestAzimuth: '260° - 285° (台灣海峽落日)',
    difficulty: '木棧道與高台步道',
    recommendedFocal: '24-70mm, 70-200mm',
    description: '曾獲 CNN 評選全球十二大最美夕陽之一！高踞紅柴坑珊瑚礁台地，俯瞰台灣海峽海平面夕陽墜海與萬丈火霞。',
    traffic: '恆春鎮往貓鼻頭方向轉關山產業道路',
    tags: ['CNN世界級夕照', '珊瑚礁海景', '海面火燒']
  },
  {
    id: 'spot-longpan',
    name: '屏東・墾丁龍磐公園',
    region: 'south',
    category: 'both',
    lat: 21.9304,
    lng: 120.8447,
    elevation: 75,
    bestAzimuth: '日出 90° 太平洋 / 日落 270° 巴士海峽',
    difficulty: '崩崖草生地，需注意強風與裂隙',
    recommendedFocal: '14-24mm 超廣角',
    description: '石灰岩溶洞崩崖地形，東臨浩瀚太平洋，南望巴士海峽。清晨太平洋第一道曙光與傍晚落日皆震撼無比。',
    traffic: '台 26 線鵝鑾鼻往佳樂水方向',
    tags: ['太平洋曙光', '崩崖海景', '無光害銀河']
  },
  {
    id: 'spot-qigu',
    name: '台南・七股頂頭額沙洲 (台版撒哈拉)',
    region: 'south',
    category: 'sunset',
    lat: 23.1009,
    lng: 120.0354,
    elevation: 5,
    bestAzimuth: '270° - 290° (極西點海邊沙丘)',
    difficulty: '沙地行走需注意防風沙',
    recommendedFocal: '16-35mm 廣角, 70-200mm 沙紋特寫',
    description: '台灣本島極西點！隨風吹拂形成細緻如浪的沙丘波紋，夕陽火燒時金黃沙丘與紅霞相映，宛如置身絲路撒哈拉。',
    traffic: '導航至七股國聖港燈塔後步行入沙洲',
    tags: ['極西點', '金色沙丘', '國聖燈塔']
  },

  // --- 東部地區 ---
  {
    id: 'spot-qixingtan',
    name: '花蓮・新城七星潭月牙灣',
    region: 'east',
    category: 'sunrise',
    lat: 24.0322,
    lng: 121.6294,
    elevation: 5,
    bestAzimuth: '70° - 90° (太平洋海平面)',
    difficulty: '鵝卵石海灘平坦',
    recommendedFocal: '16-35mm 廣角, 搭配慢速快門',
    description: '優美的新月形礫石海灣，正對浩瀚太平洋！旭日從海平面跳出時，晨彩將浪花與光滑石礫染成金色熔岩。',
    traffic: '花蓮火車站轉乘台灣好行 310 或計程車 15 分鐘',
    tags: ['月牙灣', '太平洋日出', '鵝卵石浪花']
  },
  {
    id: 'spot-sanxiantai',
    name: '台東・成功三仙台八拱跨海步橋',
    region: 'east',
    category: 'sunrise',
    lat: 23.1238,
    lng: 121.4055,
    elevation: 8,
    bestAzimuth: '80° - 100° (太平洋第一道曙光)',
    difficulty: '八拱橋步道好走',
    recommendedFocal: '16-35mm 廣角, 24-70mm',
    description: '全台灣迎接新年第一道曙光的最神聖地標！八拱巨龍橫跨太平洋巨浪，朝霞破曉時海天交映出極致紫紅光暈。',
    traffic: '台 11 線成功鎮北上三仙台遊憩區',
    tags: ['第一道曙光', '八拱跨海大橋', '海蝕火山岩']
  },
  {
    id: 'spot-nanfangao',
    name: '宜蘭・蘇澳南方澳觀景台',
    region: 'east',
    category: 'sunrise',
    lat: 24.5807,
    lng: 121.8687,
    elevation: 140,
    bestAzimuth: '75° - 95° (內埤情人灣與太平洋)',
    difficulty: '蘇花公路旁木棧平台',
    recommendedFocal: '24-70mm, 70-200mm',
    description: '居高臨下俯瞰南方澳漁港、內埤情人灣與豆腐岬！清晨太平洋朝霞火燒染紅弧形海灣與漁船出海航跡。',
    traffic: '台 9 丁線 (舊蘇花公路) 108K 處停車場',
    tags: ['情人灣晨曦', '南方澳漁港', '高空俯瞰海景']
  },

  // --- 離島地區 ---
  {
    id: 'spot-dongqing',
    name: '蘭嶼・東清灣拼板舟晨曦',
    region: 'island',
    category: 'sunrise',
    lat: 22.0561,
    lng: 121.5644,
    elevation: 3,
    bestAzimuth: '80° - 100° (太平洋海平面日出)',
    difficulty: '珊瑚礁海灣沙灘',
    recommendedFocal: '16-35mm 超廣角, 24-70mm',
    description: '達悟族傳統拼板舟靜臥於純淨果凍海面上，旭日東升朝霞映紅礁岩與獨木舟圖騰，人文與自然最極致結合。',
    traffic: '蘭嶼環島公路東清部落海灘',
    tags: ['拼板舟', '達悟族圖騰', '果凍海日出']
  },
  {
    id: 'spot-kuibishan',
    name: '澎湖・湖西奎壁山摩西分海',
    region: 'island',
    category: 'sunrise',
    lat: 23.5975,
    lng: 119.6738,
    elevation: 5,
    bestAzimuth: '75° - 95° (東方玄武岩嶼)',
    difficulty: '潮間帶礫石步道 (需配合退潮時刻)',
    recommendedFocal: '16-35mm 廣角, 搭配空拍機',
    description: '退潮時Ｓ形礫石玄武岩步道自海中浮現！清晨朝霞滿天時走在海中央步道，宛如聖經摩西分海神蹟再現。',
    traffic: '澎湖 202 縣道轉澎 14 鄉道直達奎壁山地質公園',
    tags: ['摩西分海', '玄武岩地質', '潮汐神蹟']
  }
];

if (typeof window !== 'undefined') {
  window.TAIWAN_SPOTS = TAIWAN_SPOTS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TAIWAN_SPOTS;
}
